use_frameworks!

target 'BUKDataSourcesKitDemo' do
  pod "BUKDataSourcesKit", :path => "../"

  target 'BUKDataSourcesKitTests' do
    inherit! :search_paths
    pod 'Specta'
    pod 'Expecta'
    pod 'OCMock'
  end
end
