source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BUKDataSourcesKitDemo', :exclusive => true do
  pod "BUKDataSourcesKit", :path => "../"
end

target 'BUKDataSourcesKitTests', :exclusive => true do
  pod "BUKDataSourcesKit", :path => "../"
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
