language: objective-c
osx_image: xcode7.3
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install xcpretty cocoapods --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Example/BUKDataSourcesKit.xcworkspace -scheme BUKDataSourcesKitDemo -sdk iphonesimulator -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
